/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EtherspotWallet } from "./EtherspotWallet";
export type { EtherspotWalletFactory } from "./EtherspotWalletFactory";
export * as factories from "./factories";
export { EtherspotWallet__factory } from "./factories/EtherspotWallet__factory";
export { EtherspotWalletFactory__factory } from "./factories/EtherspotWalletFactory__factory";
